FROM alpine:3.9  as base

COPY install_oracle.sh /
RUN chmod +x /install_oracle.sh && /install_oracle.sh

FROM alpine:3.9 

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_21_3:$LD_LIBRARY_PATH

COPY --from=base /opt/oracle/ /opt/oracle/

RUN apk add --update --no-cache libaio